language: julia
os:
    - linux
    - osx
julia:
    - 1.2
notifications:
    email: false
after_success:
  - julia -e 'import Pkg; import TensorDecompositions2; cd(joinpath(dirname(pathof(TensorDecompositions2)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
