language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("TensorDecompositions"))`); Pkg.pin("TensorDecompositions"); Pkg.resolve()'
  - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage test/runtests.jl; fi
  - if [ $JULIAVERSION = "juliareleases" ]; then julia test/runtests.jl; fi
