language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("TensorDecompositions", coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("TensorDecompositions")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

